### ISSUE TITLE
Serializing a JsonDict brings wrong result...

### ISSUE THREAD

**Issue by windischb** [wmjordan/PowerJSON#11]
Hi!

There a Problems with Deserializing a json String using PowerJson 3.0.0-alpha3
I have created a simple C# Example which brings a wrong result...

```
PowerJson.Json.Manager.UseExtensions = false;
var json = "{\"name\":\"Test\",\"data\":{ \"IsTrue\": true, \"FirstName\": \"Firstname\"}}";
var obj = PowerJson.Json.Parse(json);
Console.WriteLine(PowerJson.Json.ToJson(obj));
```

Result is `[{"name":{}},{"data":{"Capacity":4}}]`
instead of `{"name":"Test","data":{ "IsTrue": true, "FirstName": "Firstname"}}`

**Comment by wmjordan** [comment]
Thank you for telling me this.
I'd just committed a new version to fix this issue.

**Comment by windischb** [comment]
Many thanks! It's working now as expected!
