### ISSUE TITLE
Occassional remoting errors

### ISSUE THREAD

**Issue by deandob** [wmjordan/PowerJSON#3]
Hi, thanks for the efforts to improve fastJSON.

I get an occasional error where powerJSON can't serialise a properly formed dictionary object, I get remoting errors about the object being disconnected (possibly garbage collected if you are using app domains?). Never had this problem with fastJSON until I swapped to powerJSON - can you have a look at the error below and provide advice? Thanks.

Error: {"Object '/1661b37f_5d4b_4134_9971_8e0320009557/ga7gjznovzi+odu2tlo44eoo_3.rem' has been disconnected or does not exist at the server."}

Stack:    at System.Object.GetHashCode()
   at System.Collections.Generic.ObjectEqualityComparer`1.GetHashCode(T obj)
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at fastJSON.JsonSerializer.WriteObject(Object obj)
   at fastJSON.JsonSerializer.WriteObject(Object obj)
   at fastJSON.JsonSerializer.WriteStringDictionary(IDictionary dic)
   at fastJSON.JsonSerializer.ConvertToJSON(Object obj, ReflectionCache cache)
   at HAConsole.HAServices.HomeServices.SendChannelNames(String user, HAMessageStruc clientMessage) in C:\Users\deandob\Documents\GitHub\HAConsole\HAConsole\HAServices.vb:line 616
   at HAConsole.HAServices.HomeServices.HandleMessage(Object Message) in C:\Users\deandob\Documents\GitHub\HAConsole\HAConsole\HAServices.vb:line 524

My function: fastJSON.JSON.ToJSON(Plugins) where Plugins is a fully formed dictionary object
local object: Private Plugins As New ConcurrentDictionary(Of String, Structures.PlugStruc)

**Comment by wmjordan** [comment]
Could you please provide more information about the detail about the `PlugStruc` type and whether the items in the `ConcurrentDictionary<string, PlugStruc>` would be disposed or altered during serialization?

**Comment by deandob** [comment]
I can view the entire object in the debugger so it is not disposed. Also I can detect a pattern, don't get this error when the app first starts, but it will start after a couple of minutes running. 

Also, not sure if it is related but I had to change all the Dictionary definitions to interfaces (IDictionary) which wasn't necessary in fastJSON. 

PlugStruc is a VB structure as below and Plugins is marshalled. Plugins is initialized with data but stays static during runtime with the exception of the lastMsg field which is changed every second or so.

```
<Serializable()>
Public Structure PlugStruc
    Public Category As String
    Public ClassName As String
    Public Desc As String
    Public Type As String
    Public Status As String
    Public Channels As List(Of Structures.ChannelStruc)
    Public NodeRef As String
    Public lastMsg As HAMessageStruc                    ' Used to avoid sending back the same message to the plugin
    Public AssRef As Plugins.IHAPlugin                 ' Pointer to the plugin
End Structure

<Serializable()>
Public Structure ChannelStruc
    Public Name As String
    Public Desc As String
    Public Type As String
    Public IO As String
    Public Min As Single
    Public Max As Single
    Public Units As String
    Public Attribs As List(Of Structures.ChannelAttribStruc)
    Public Value As String
End Structure

<Serializable()>
Public Structure ChannelAttribStruc
    Public Name As String
    Public Type As String
    Public Value As String
End Structure
```

Thanks for helping.

**Comment by wmjordan** [comment]
Thank you for the information.
I saw that the closest exception in the stack trace was from the `WriteObject(Object obj)` method, which tried to obtain a member via the `TryGetValue` method.
1)Could you please provide a little more information from the debugger while the exception is thrown, what key is trying to get by the `TryGetValue` method and what is in the `Dictionary` instance?
2)You said that _I had to change all the Dictionary definitions to interfaces (IDictionary) which wasn't necessary in fastJSON_, but I did not see any definition about the `IDictionary` in your code.

**Comment by deandob** [comment]
NodeKeyValueCollection from ListDictionaryInternal from GetHashCode() is the data from the exception thrown. Its not easy to copy from the Visual Studio IDE but I can send you a screenshot if you want of the full exception.

Not sure the change from Dictionary to IDictionary is related, but I needed to change all my dictionary definitions where dictionary objects were being processed by powerJSON (wouldn't compile), which wasn't necessary with fastJSON. It may not be related but I called this out as it was the only change I made between switching from fastJSON to powerJSON when the object disconnection error started.

**Comment by wmjordan** [comment]
PowerJSON should be able to process Dictionary types. Could you provide me an example which can be directly processed by fastJSON but not by PowerJSON?

You can upload screen shots to GitHub directly by clicking the link below the textbox where you wrote the comment.

**Comment by deandob** [comment]
wm,
I have worked around this problem by copying the object into a temporary object with just the fields I need. Even though I was using ConcurrentDictionary in a multi-threaded environment, the object was being queued for update in other threads and also included reference pointers. Possibly too complex to serialize, although it was working fine in fastJSON and powerJSON only started to raise exceptions after the object was 5 minutes old - quite strange.

**Comment by wmjordan** [comment]
I am sorry that I did not help you out.
You can annotate the member you don't need to serialize with the `[JsonInclude(false)]` attribute.

**Comment by deandob** [comment]
Helpful wm, I didn't know that. Seems to work so far. thanks.

**Comment by wmjordan** [comment]
I  am curious about the issue that you posted _I had to change all the `Dictionary` definitions to interfaces (`IDictionary`) which wasn't necessary in fastJSON_. I still could not figure out why those changes had to be made. Could you please show me some sample code so I can inspect it?
