### ISSUE TITLE
missing overloads

### ISSUE THREAD

**Issue by BrannonKing** [wmjordan/PowerJSON#5]
I just made my first attempt at using PowerJSON. I had these hiccups:
1. I need overloads for Deserialize(data, type, manager). Also, it's important to make sure that the parameters used internally by that method come from the manager rather than the global. This method is wrong: `public static T ToObject<T>(string json, SerializationManager manager)` presently. 
2. I expected to see an overload for Serialize that took a type. If the type of the value passed in matches the type passed in then you don't need to include the $type data. I don't see anyway for that to be determined automatically in the current system.
3. I don't understand why the JsonDeserializer and JsonSerializer classes are internal. They are easy enough to use. They don't store state and could be reusuable. I would prefer to instantiate one of each and use them in my wrapper.

**Comment by BrannonKing** [comment]
I get the impression that everyone using this must just go with the default manager (and modify the default parameters). I'll do that for now.

**Comment by wmjordan** [comment]
Thank you very much for the feedback.
Usually working with the default manager and parameter is sufficient.
If it does not meet your requirements, you can modify the source code to get method `Deserialize(data, type, manager)`.
At present, PowerJSON is a drop-in replacement for fastJSON, it has to follow the naming and usage of it. Thus it is natural for you (and me as well) to encounter problem 2. Currently you might want to disable the extensions via the setting in `JSONParameters`--and I always do that.
About problem 3, `JsonDeserializer` and `JsonSerializer` do store some states (for example, circular reference detection and types mapper) and in multi-threading environments such as ASP.NET, you can not share the same `JsonDeserializer` and `JsonSerializer` across different threads, thus the serializers can not be reused.

**Comment by BrannonKing** [comment]
Pull request is in.

**Comment by wmjordan** [comment]
Merged.
